import { StyleSheet } from 'react-native'

export const theme = {
  colors: {
    textPrimary: '#24292e',
    textSecondary: '#b8c0c9', //#586069',
    textLight: '#ffffff',
    error: '#d73a4a',
    primary: '#0366d6',
    mainBackground: '#e1e4e8',
    panel: '#ffffff',
  },
  fontSizes: {
    body: 14,
    subheading: 16,
  },
  fonts: {
    android: 'Roboto',
    ios: 'Arial',
    native: 'System',
    web: 'System',
  },
  fontWeights: {
    normal: '400',
    bold: '700',
  },
  sizes: {
    panelHeight: 60,
    inputHeight: 40,
    gap: 10,
    radius: 5,
    border: 2,
    widthPct: '96%',
    marginPct: '2%',
  },
}

export const styles = StyleSheet.create({
  mainContainer: {
    maxWidth: 800,
    flexGrow: 1,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'stretch',
    backgroundColor: theme.colors.mainBackground,
    padding: 0,
  },
  itemContainer: {
    flex: 1,
    backgroundColor: theme.colors.panel,
    padding: theme.sizes.gap,
  },
  appBarContainer: {
    height: theme.sizes.inputHeight,
    backgroundColor: theme.colors.textPrimary,
    flexDirection: 'row',
  },
  panel: {
    backgroundColor: theme.colors.panel,
    // width: '100%',
    //height: theme.sizes.panelHeight,
    margin: 0,
    alignItems: 'stretch',
  },
  appBarAlign: {
    GapHorizontal: 10,
    alignItems: 'center',
  },
  appBarTab: {
    padding: 8,
  },
  textInput: {
    width: theme.sizes.widthPct,
    marginLeft: theme.sizes.marginPct,
    height: theme.sizes.inputHeight,
    marginVertical: theme.sizes.gap,
    color: theme.colors.textPrimary,
    placeholderTextColor: theme.colors.textSecondary,
    backgroundColor: theme.colors.panel,
    borderWidth: theme.sizes.border,
    borderRadius: theme.sizes.radius,
    paddingHorizontal: theme.sizes.gap,
  },
  error: {
    height: theme.sizes.panelHeight - theme.sizes.inputHeight,
    marginTop: -10,
    marginBottom: 0,
    paddingLeft: 10,
    backgroundColor: theme.colors.panel,
  },
  submit: {
    //alignSelf: 'stretch',
    textAlign: 'center',
    color: theme.colors.textLight,
    backgroundColor: theme.colors.primary,
    maxWidth: theme.sizes.widthPct,
    height: theme.sizes.inputHeight,
    margin: theme.sizes.gap,
    borderWidth: theme.sizes.border,
    borderRadius: theme.sizes.radius,
    paddingVertical: theme.sizes.gap,
  },
  topRow: {
    flexDirection: 'row',
    gap: theme.sizes.gap,
    alignItems: 'flex-start',
  },
  infoColumn: {
    maxWidth: '80%',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  statsItem: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBlock: theme.sizes.gap / 2,
  },
  languageItem: {
    backgroundColor: theme.colors.primary,
    padding: 5,
    borderRadius: theme.sizes.radius,
    marginTop: 5,
    marginBottom: theme.sizes.radius,
  },
  tinyLogo: {
    alignSelf: 'center',
    width: 50,
    height: 50,
  },
  rating: {
    width: theme.sizes.inputHeight,
    height: theme.sizes.inputHeight,
    borderWidth: theme.sizes.border,
    borderRadius: theme.sizes.inputHeight / 2,
    borderColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subheading: {
    paddingBottom: 5,
    //  paddingTop: 5,
  },
  separator: {
    height: theme.sizes.gap,
  },
  buttonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortPickerWeb: {
    width: theme.sizes.widthPct,
    height: theme.sizes.inputHeight,
    alignSelf: 'center',
    backgroundColor: theme.colors.mainBackground,
    marginTop: theme.sizes.gap,
    borderWidth: theme.sizes.border,
    borderRadius: theme.sizes.radius,
  },
  sortPickerIOS: {
    backgroundColor: theme.colors.mainBackground,
    color: theme.colors.primary,
    fontWeight: 'bold',
  },
  clearButton: {
    textAlign: 'center',
    color: theme.colors.textSecondary,
    backgroundColor: theme.colors.panel,
    padding: 1,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: theme.colors.textSecondary,
    width: 20,
    height: 20,
    left: -10,
  },
})
